### ISSUE TITLE
CRDB: unable to run twitter

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#13]
```
15:31:44,588 (DBWorkload.java:552) ERROR - Unexpected error when running benchmarks.
java.io.FileNotFoundException: config/traces/twitter_tweetids.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.oltpbenchmark.benchmarks.twitter.util.TransactionSelector.<init>(TransactionSelector.java:53)
	at com.oltpbenchmark.benchmarks.twitter.TwitterBenchmark.makeWorkersImpl(TwitterBenchmark.java:56)
	at com.oltpbenchmark.api.BenchmarkModule.makeWorkers(BenchmarkModule.java:200)
	at com.oltpbenchmark.DBWorkload.runWorkload(DBWorkload.java:802)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:550)
```

**Comment by timveil** [comment]
txt files added, another error code was encountered and that was also fixed
