### ISSUE TITLE
CRDB: TPC-H Q18 not working with CRDB 2.2 Alpha

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#14]
```
[ERROR] 2019-02-13 16:14:55,193 [TPCHWorker<000>]  com.oltpbenchmark.ThreadBench uncaughtException - Unexpected fatal, error in 'TPCHWorker<000>' when executing 'com.oltpbenchmark.benchmarks.tpch.procedures.Q18/18' [COCKROACHDB]
java.lang.RuntimeException: Unexpected fatal, error in 'TPCHWorker<000>' when executing 'com.oltpbenchmark.benchmarks.tpch.procedures.Q18/18' [COCKROACHDB]
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:560)
	at com.oltpbenchmark.api.Worker.run(Worker.java:274)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: memory budget exceeded: 10240 bytes requested, 134215680 currently allocated, 134217728 bytes in budget
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at com.oltpbenchmark.benchmarks.tpch.procedures.GenericQuery.run(GenericQuery.java:37)
	at com.oltpbenchmark.benchmarks.tpch.TPCHWorker.executeWork(TPCHWorker.java:43)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:389)
	... 2 more
```

**Comment by timveil** [comment]
resolved by making the following change:
* set `-max-sql-memory=4GB` on each node
