### ISSUE TITLE
Request Config parameter for setting Connection Pool size

### ISSUE THREAD

**Issue by drewdeally** [timveil-cockroach/oltpbench#15]
While testing at a higher Scale Factor encountered 

```
Exception in thread "main" java.lang.RuntimeException: Failed to execute threads: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
    at com.oltpbenchmark.util.ThreadUtil.run(ThreadUtil.java:298)
    at com.oltpbenchmark.util.ThreadUtil.runNewPool(ThreadUtil.java:262)
    at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:276)
    at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:734)
    at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:442)
Caused by: java.lang.RuntimeException: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
    at com.oltpbenchmark.api.LoaderThread.run(LoaderThread.java:33)
    at com.oltpbenchmark.util.ThreadUtil$LatchRunnable.run(ThreadUtil.java:332)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
    at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:669)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:183)
    at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:148)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
    at com.oltpbenchmark.api.BenchmarkModule.getConnection(BenchmarkModule.java:117)
    at com.oltpbenchmark.api.LoaderThread.run(LoaderThread.java:27)
    ... 4 more


```

For TPCC, as we scale to 100 or 1000 warehouses it appears more connections are required.

**Comment by timveil** [comment]
added `<poolsize>` as a xml config option.  the default value is set to `25`
