### ISSUE TITLE
AuctionMark exceptions

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#40]
after resolving #4, run into multiple exceptions like below.  need to better understand this benchmark to know if this behavior is expected.  check with @apavlo.
```
[WARN] 2020-05-14 20:18:54,067 [AuctionMarkWorker<001>]  com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker executeWork - Unable to execute GetItem because it is not ready
[WARN] 2020-05-14 20:18:54,106 [AuctionMarkWorker<001>]  com.oltpbenchmark.api.Worker doWork - PSQLException thrown when executing 'com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem/07' on 'AuctionMarkWorker<001>' [Message='ERROR: duplicate key value (i_id,i_u_id)=(6597070160083,393427) violates unique constraint "primary"', ErrorCode='0', SQLState='23505']
org.postgresql.util.PSQLException: ERROR: duplicate key value (i_id,i_u_id)=(6597070160083,393427) violates unique constraint "primary"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:125)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at com.oltpbenchmark.benchmarks.auctionmark.procedures.NewItem.run(NewItem.java:171)
	at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeNewItem(AuctionMarkWorker.java:789)
	at com.oltpbenchmark.benchmarks.auctionmark.AuctionMarkWorker.executeWork(AuctionMarkWorker.java:386)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:374)
	at com.oltpbenchmark.api.Worker.run(Worker.java:273)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timveil** [comment]
refactored much of this benchmark to properly close jdbc object and user getters/setters to update objects.  also cleaned up equals/hashcode implementations.  this issue has gone away
