### ISSUE TITLE
CRDB: unable to run chbenchmark

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#5]
```
14:37:12,169 (Worker.java:417) WARN  - PSQLException thrown when executing 'Q15/20' on 'CHBenCHmarkWorker<001>' [Message='ERROR: current transaction is aborted, commands ignored until end of transaction block', ErrorCode='0', SQLState='25P02']
org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:244)
	at com.oltpbenchmark.benchmarks.chbenchmark.queries.Q15.run(Q15.java:72)
	at com.oltpbenchmark.benchmarks.chbenchmark.CHBenCHmarkWorker.executeWork(CHBenCHmarkWorker.java:37)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
	at com.oltpbenchmark.api.Worker.run(Worker.java:294)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: column "supplier_no" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:244)
	at com.oltpbenchmark.benchmarks.chbenchmark.queries.Q15.run(Q15.java:69)
	... 4 more
```

**Comment by timveil** [comment]
all missing column errors have been resolved.  now the benchmark throws an error when terminating.  I think this is related to hung chbenchmark worker threads...

```
[DEBUG] 2019-02-11 20:49:41,728 [TPCCWorker<000>]  com.oltpbenchmark.api.Worker tearDown - calling teardown error = false
[WARN] 2019-02-11 20:50:11,162 [CHBenCHmarkWorker<001>]  com.oltpbenchmark.api.Worker doWork - PSQLException thrown when executing 'Q18/23' on 'CHBenCHmarkWorker<001>' [Message='An I/O error occurred while sending to the backend.', ErrorCode='0', SQLState='08006']
org.postgresql.util.PSQLException: An I/O error occurred while sending to the backend.
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:335)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.oltpbenchmark.benchmarks.chbenchmark.queries.GenericQuery.run(GenericQuery.java:76)
	at com.oltpbenchmark.benchmarks.chbenchmark.CHBenCHmarkWorker.executeWork(CHBenCHmarkWorker.java:37)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:392)
	at com.oltpbenchmark.api.Worker.run(Worker.java:293)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:308)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	... 9 more
[DEBUG] 2019-02-11 20:50:11,163 [CHBenCHmarkWorker<001>]  com.oltpbenchmark.api.Worker doWork - CHBenCHmarkWorker<001> Q18/23 Result: UNKNOWN
[ERROR] 2019-02-11 20:50:11,164 [CHBenCHmarkWorker<001>]  com.oltpbenchmark.ThreadBench uncaughtException - Unexpected fatal, error in 'CHBenCHmarkWorker<001>' when executing 'Q18/23' [COCKROACHDB]
java.lang.RuntimeException: Unexpected fatal, error in 'CHBenCHmarkWorker<001>' when executing 'Q18/23' [COCKROACHDB]
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:546)
	at com.oltpbenchmark.api.Worker.run(Worker.java:293)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:783)
	at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:1655)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:429)
	... 2 more
```

**Comment by timveil** [comment]
worker connection and transaction refactoring in `worker-connection` branch has resolved this issue

**Comment by timveil** [comment]
not actually fixed... very similar to #12, similar query that hangs

**Comment by timveil** [comment]
really a duplicate of #12... see that issue for resolution
