### ISSUE TITLE
CRDB: unable to run chbenchmark

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#6]
```
14:37:19,474 (Worker.java:417) WARN  - PSQLException thrown when executing 'Q9/14' on 'CHBenCHmarkWorker<002>' [Message='ERROR: column "l_year" does not exist', ErrorCode='0', SQLState='42703']
org.postgresql.util.PSQLException: ERROR: column "l_year" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:106)
	at com.oltpbenchmark.benchmarks.chbenchmark.queries.GenericQuery.run(GenericQuery.java:76)
	at com.oltpbenchmark.benchmarks.chbenchmark.CHBenCHmarkWorker.executeWork(CHBenCHmarkWorker.java:37)
	at com.oltpbenchmark.api.Worker.doWork(Worker.java:386)
	at com.oltpbenchmark.api.Worker.run(Worker.java:294)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by timveil** [comment]
these issues have been resolved
