### ISSUE TITLE
CRDB: unable to run epinions

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#7]
```
14:47:50,740 (EpinionsBenchmark.java:100) ERROR - ERROR: relation "nulluseracctnull" does not exist
org.postgresql.util.PSQLException: ERROR: relation "nulluseracctnull" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
	at com.oltpbenchmark.benchmarks.epinions.EpinionsBenchmark.makeWorkersImpl(EpinionsBenchmark.java:70)
	at com.oltpbenchmark.api.BenchmarkModule.makeWorkers(BenchmarkModule.java:200)
	at com.oltpbenchmark.DBWorkload.runWorkload(DBWorkload.java:802)
	at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:550)
```

**Comment by timveil** [comment]
busted code was surrounding table name with null catalog separator; improved logic for method.
