### ISSUE TITLE
no workable implementation for LinkBench

### ISSUE THREAD

**Issue by timveil** [timveil-cockroach/oltpbench#9]
loader needs to be fixed, wrong tables referenced in loader
```
19:38:01,771 (BenchmarkModule.java:293) DEBUG - Using legacy LinkBenchLoader.load() method
Exception in thread "main" java.lang.NullPointerException
    at com.oltpbenchmark.util.SQLUtil.getInsertSQL(SQLUtil.java:374)
    at com.oltpbenchmark.util.SQLUtil.getInsertSQL(SQLUtil.java:355)
    at com.oltpbenchmark.benchmarks.linkbench.LinkBenchLoader.load(LinkBenchLoader.java:54)
    at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:296)
    at com.oltpbenchmark.api.BenchmarkModule.loadDatabase(BenchmarkModule.java:258)
    at com.oltpbenchmark.DBWorkload.runLoader(DBWorkload.java:794)
    at com.oltpbenchmark.DBWorkload.main(DBWorkload.java:525)
```

**Comment by timveil** [comment]
this benchmark is not properly implemented in the master, there is a un-merged pull request that looks to be complete but i can't get that working either.  not sure why this code even exists.  may remove all together.

**Comment by timveil** [comment]
linkbench has been removed
